version: '3'
services:
  go-app:
    build: .
    environment:
      - JWT_SECRET=abc
      - CONNECTION_STRING=postgres://postgres_user:postgres_password@postgres_db:5432/pgdb?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres_db
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "9000:80"
    depends_on:
      - postgres_db
    volumes:
      - my-data:/var/lib/pgadmin

volumes:
  my-data:
